### ISSUE TITLE
Graphic Work

### ISSUE THREAD

**Issue by thepacc** [jakecaputo/thepacc#15]
n the demo site, instead of scrolling between the logo and the thylicine on the grey background, if we could create three images, maybe with the images from the original site header and some, black and white like the original site header, with some sales type text, and some color, that might be nice. Or maybe something with some sales type text on one side a diagonal line separating it from one of those pictures. then when it switches, the text could be on the other side, with a one of the other images on the opposite side, then the third woudl be the text back on the side it started.

The three text sections i would love to get your thoughts on, but i am thinking...

Professionally Designed
Interactive admin panel
$$$ value all for the price of hosting (not sure what the site would go for from scratch, i am thinking over 3k.

or... instead of selling points we could do...

Explore your world
Share your findings
Build a following

Would love your thoughts on that before we do it :)

**Comment by jakecaputo** [comment]
Yeah, a custom site would cost a lot, but people don't do that. Especially the market we're after. They'd do a free Tumblr or a free WordPress site. If they're looking to spend money, they'd grab a WP theme or go to squarespace. I'd lean towards the

Explore your world
Share your findings
Build a following

I think we need to promote the community aspect of this. That's what we have that Tumblr and WP don't.

**Comment by jakecaputo** [comment]
Done!
