### ISSUE TITLE
Button Color Change

### ISSUE THREAD

**Issue by thepacc** [jakecaputo/thepacc#16]
Can we change Create a Site on the bottom of the group site page from Red to Green or blue? Red gives me pause, like physiologically my brain says stop :)

Unless you think red is prefect, would love your thoughts.

**Comment by jakecaputo** [comment]
I think red is perfect. Statistically, red buttons are clicked more than any other color buttons. There a tons of usability studies out there.

**Comment by thepacc** [comment]
sounds good, red button it is :)
